# Generated by Django 4.2.3 on 2023-08-14 02:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_id', models.PositiveIntegerField()),
                ('level', models.PositiveIntegerField(choices=[(0, 'basic'), (1, 'intermediate'), (2, 'advanced')])),
                ('type', models.CharField(choices=[('b1', 'Hair/B1'), ('b2', 'Hair/B2'), ('b3', 'Hair/B3'), ('g1', 'Hair/G1'), ('g2', 'Hair/G2'), ('g3', 'Hair/G3'), ('c1', 'Top/C1'), ('c2', 'Top/C2'), ('c3', 'Top/C3'), ('c4', 'Top/C4'), ('c5', 'Top/C5'), ('c6', 'Top/C6'), ('pb1', 'Bottom/Pb1'), ('pb2', 'Bottom/Pb2'), ('pb3', 'Bottom/Pb3'), ('pg1', 'Bottom/Pg1'), ('pg2', 'Bottom/Pg2'), ('pg3', 'Bottom/Pg3'), ('s1', 'Shoes/S1'), ('s2', 'Shoes/S2'), ('s3', 'Shoes/S3'), ('s4', 'Shoes/S4'), ('s5', 'Shoes/S5'), ('s6', 'Shoes/S6')], max_length=10)),
                ('lucky', models.FloatField(default=1)),
                ('exp', models.FloatField(default=0)),
                ('coupon', models.TextField(blank=True, null=True)),
                ('custom', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='address')),
            ],
            options={
                'db_table': 'gear',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WeekTask',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='task', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('week_start', models.DateField(default=django.utils.timezone.now)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wear',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wear', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bottom', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottom', to='api.gear')),
                ('hair', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hair', to='api.gear')),
                ('shoes', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='api.gear')),
                ('target', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='api.gear')),
                ('top', models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top', to='api.gear')),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bicep_curl', '二頭彎舉'), ('push_up', '伏地挺身'), ('squat', '深蹲')], default='bicep_curl', max_length=15)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('count', models.PositiveIntegerField(default=0)),
                ('accuracy', models.FloatField(default=0.0)),
                ('gear', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.gear')),
            ],
            options={
                'db_table': 'exercise',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('dumbbell', '初級小物/dumbbell'), ('energy_drink', '中級小物/energy_drink'), ('protein_powder', '高級小物/protein_powder')], default='dumbbell', max_length=20)),
                ('amount', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'thing',
                'managed': True,
                'unique_together': {('user', 'type')},
            },
        ),
    ]
