# Generated by Django 4.2.3 on 2023-07-08 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'things',
                'managed': True,
                'unique_together': {('user', 'type')},
            },
        ),
        migrations.CreateModel(
            name='Gear',
            fields=[
                ('nid', models.AutoField(db_column='Nid', primary_key=True, serialize=False)),
                ('hash', models.CharField(blank=True, max_length=255, null=True)),
                ('level', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('work_max', models.IntegerField(blank=True, null=True)),
                ('exp', models.FloatField(blank=True, null=True)),
                ('lucky', models.FloatField(blank=True, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('coupon', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'eq',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('timestamp', models.DateTimeField()),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'exercise',
                'managed': True,
                'unique_together': {('user', 'timestamp')},
            },
        ),
    ]
