# Generated by Django 4.2.3 on 2023-08-21 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='coupon_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
