# Generated by Django 4.2.3 on 2023-07-29 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exercise_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='count',
        ),
    ]
