# Generated by Django 4.2.3 on 2023-07-09 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_remove_gear_nid_gear_id_alter_gear_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(blank=True, choices=[('PUSH_UP', '伏地挺身'), ('SQUAT', '深蹲'), ('BICEPS_CURL', '二頭彎舉')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='gear',
            name='color',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='level',
            field=models.CharField(blank=True, choices=[('LOW', 'low'), ('MID', 'mid'), ('HIGH', 'high')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
