# Generated by Django 4.2.3 on 2023-07-30 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_alter_user_address'),
        ('api', '0003_remove_exercise_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekTask',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='task', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('week_start', models.DateField(default=django.utils.timezone.now)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'managed': True,
            },
        ),
        migrations.RemoveField(
            model_name='gear',
            name='token_id',
        ),
        migrations.AddField(
            model_name='exercise',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='accuracy',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='gear',
            name='level',
            field=models.CharField(choices=[('BASIC', '初階'), ('INTERMEDIATE', '中階'), ('ADVANCED', '進階')], max_length=15),
        ),
        migrations.AlterField(
            model_name='gear',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
