# Generated by Django 4.2.3 on 2023-07-09 04:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_exercise_id_thing_id_alter_exercise_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
