# Generated by Django 4.2.3 on 2023-07-30 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_weektask_remove_gear_token_id_exercise_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='thing',
            name='level',
            field=models.PositiveIntegerField(choices=[(0, 'BASIC/初級小物'), (1, 'INTERMEDIATE/中級小物'), (2, 'HIGH_END/高級小物')]),
        ),
    ]
