# Generated by Django 4.2.3 on 2023-07-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_exercise_timestamp_alter_thing_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
        migrations.AlterField(
            model_name='gear',
            name='level',
            field=models.PositiveIntegerField(choices=[(0, 'BASIC/初階'), (1, 'INTERMEDIATE/中階'), (2, 'ADVANCED/進階')]),
        ),
        migrations.AlterField(
            model_name='thing',
            name='level',
            field=models.PositiveIntegerField(choices=[(0, '初級小物'), (1, '中級小物'), (2, '高級小物')]),
        ),
    ]
