# Generated by Django 4.2.3 on 2023-07-31 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_exercise_user_alter_gear_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='color',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'STYLE A'), (1, 'STYLE B'), (2, 'STYLE C')]),
        ),
        migrations.AlterField(
            model_name='gear',
            name='level',
            field=models.PositiveIntegerField(choices=[(0, 'BASIC'), (1, 'INTERMEDIATE'), (2, 'ADVANCED')]),
        ),
        migrations.AlterField(
            model_name='gear',
            name='type',
            field=models.PositiveIntegerField(blank=True, choices=[(0, '上衣/二頭彎舉'), (1, '下著/伏地挺身'), (2, '鞋子/深蹲')]),
        ),
    ]
