# Generated by Django 4.2.3 on 2023-07-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_exercise_unique_together_alter_exercise_gear_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='type',
        ),
        migrations.AlterField(
            model_name='gear',
            name='level',
            field=models.CharField(blank=True, choices=[('BASIC', '初階'), ('INTERMEDIATE', '中階'), ('ADVANCED', '進階')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='gear',
            name='type',
            field=models.IntegerField(blank=True, choices=[(0, '帽子/伏地挺身'), (1, '手套/二頭彎舉'), (2, '鞋子/深蹲')], null=True),
        ),
        migrations.AlterField(
            model_name='thing',
            name='level',
            field=models.CharField(blank=True, choices=[('BASIC', '初級小物'), ('INTERMEDIATE', '中級小物'), ('HIGH_END', '高級小物')], max_length=255, null=True),
        ),
    ]
