# Generated by Django 4.2.3 on 2023-07-31 17:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_gear_color_alter_gear_level_alter_gear_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gear',
            name='color',
            field=models.PositiveIntegerField(blank=True, choices=[(0, 'STYLE_A'), (1, 'STYLE_B'), (2, 'STYLE_C')]),
        ),
    ]
