# Generated by Django 4.2.3 on 2023-08-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_exercise_timestamp_alter_gear_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gear',
            name='color',
        ),
        migrations.RemoveField(
            model_name='gear',
            name='lucky',
        ),
        migrations.AddField(
            model_name='exercise',
            name='type',
            field=models.PositiveIntegerField(choices=[(0, '二頭彎舉'), (1, '伏地挺身'), (2, '深蹲')], default=0),
        ),
        migrations.AlterField(
            model_name='gear',
            name='exp',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='gear',
            name='level',
            field=models.PositiveIntegerField(choices=[(0, 'regular'), (1, 'advanced'), (2, 'high-end'), (3, 'epic')]),
        ),
        migrations.AlterField(
            model_name='gear',
            name='type',
            field=models.CharField(choices=[('b1', '髮型/男/1'), ('b2', '髮型/男/2'), ('b3', '髮型/男/3'), ('g1', '髮型/女/1'), ('g2', '髮型/女/2'), ('g3', '髮型/女/3'), ('c1', '上衣/1'), ('c2', '上衣/2'), ('c3', '上衣/3'), ('c4', '上衣/4'), ('c5', '上衣/5'), ('c6', '上衣/6'), ('pb1', '下著/男/1'), ('pb2', '下著/男/2'), ('pb3', '下著/男/3'), ('pg1', '下著/女/1'), ('pg2', '下著/女/2'), ('pg3', '下著/女/3'), ('s1', '鞋子/1'), ('s2', '鞋子/2'), ('s3', '鞋子/3'), ('s4', '鞋子/4'), ('s5', '鞋子/5'), ('s6', '鞋子/6')], default='c3', max_length=5),
        ),
    ]
