# Generated by Django 4.2.3 on 2023-08-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_gear_work_max_gear_lucky_alter_gear_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gear',
            name='token_id',
            field=models.PositiveIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
