# Generated by Django 4.2.3 on 2023-08-05 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_gear_token_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gear',
            name='lucky',
            field=models.PositiveIntegerField(choices=[(0, 'regular'), (1, 'advanced'), (2, 'high-end'), (3, 'epic')], default=0),
        ),
    ]
