# Generated by Django 4.2.3 on 2023-08-06 18:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_gear_custom_alter_gear_coupon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thing',
            old_name='level',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='gear',
            name='lucky',
            field=models.FloatField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='thing',
            unique_together={('user', 'type')},
        ),
    ]
