# Generated by Django 4.2.3 on 2023-08-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_rename_level_thing_type_alter_gear_lucky_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thing',
            name='type',
            field=models.CharField(choices=[('dumbbel', '初級小物'), ('energy_drink', '中級小物'), ('protein_powder', '高級小物')], default='dumbbel', max_length=20),
        ),
    ]
