# Generated by Django 4.2.3 on 2023-08-07 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_gear_type_alter_thing_type_wear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wear',
            name='bottom',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bottom', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='hair',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hair', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='shoes',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='target',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='target', to='api.gear'),
        ),
        migrations.AlterField(
            model_name='wear',
            name='top',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='top', to='api.gear'),
        ),
    ]
