# Generated by Django 4.2.3 on 2023-08-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_wear_bottom_alter_wear_hair_alter_wear_shoes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='type',
            field=models.CharField(choices=[('bicep_curl', '二頭彎舉'), ('push_up', '伏地挺身'), ('squat', '深蹲')], default='bicep_curl', max_length=15),
        ),
    ]
