# Generated by Django 4.2.3 on 2023-07-29 17:29

from django.db import migrations, models
import siwe.siwe


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nonce',
            field=models.CharField(default=siwe.siwe.generate_nonce, max_length=36),
        ),
    ]
