# Generated by Django 4.2.3 on 2023-07-29 18:25

import api.utils.ethereum
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(default=api.utils.ethereum.generate_random_ethereum_address, max_length=42, unique=True),
        ),
    ]
